name = "exp"
description = "A description of the experiment"
store = "/Users/akeles/Programming/projects/PbtBenchmark/etna2/exp/store.json"

[[workloads]]
name = "BST"
language = "Racket"

[[workloads]]
name = "BST"
language = "Rocq"

[[workloads]]
name = "BST"
language = "Haskell"

[[workloads]]
name = "BST"
language = "OCaml"

[[workloads]]
name = "BST"
language = "Rust"

[[workloads]]
name = "RBT"
language = "Rust"

[[workloads]]
name = "RBT"
language = "Rocq"

[[workloads]]
name = "RBT"
language = "Racket"

[[workloads]]
name = "RBT"
language = "OCaml"

[[workloads]]
name = "STLC"
language = "Rocq"

[[workloads]]
name = "STLC"
language = "Haskell"

[[workloads]]
name = "STLC"
language = "Rust"

[[workloads]]
name = "STLC"
language = "OCaml"

[[workloads]]
name = "RBT"
language = "Haskell"

[[workloads]]
name = "STLC"
language = "Racket"
