name: etna-bst

dependencies:
    - base >= 4.7 && < 5
    - etna-lib
    - QuickCheck
    - smallcheck
    - leancheck
    - generic-random
    - deepseq

library:
    source-dirs: src

executables:
    bst:
        main: Main.hs
        source-dirs: app/bst
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-bst
    bst-sampler:
        main: Main.hs
        source-dirs: app/bst-sampler
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-bst
