name: etna-stlc

dependencies:
    - base >= 4.7 && < 5
    - etna-lib
    - QuickCheck
    - smallcheck
    - leancheck
    - generic-random
    - deepseq

library:
    source-dirs: src

executables:
    stlc:
        main: Main.hs
        source-dirs: app/stlc
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-stlc
    stlc-sampler:
        main: Main.hs
        source-dirs: app/stlc-sampler
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-stlc

