resolver: lts-19.6
compiler: ghc-9.0.2
allow-newer: true
system-ghc: true

extra-include-dirs:
    - /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/ffi


packages:
    - .
    - ../common/etna-lib
