name: etna-rbt

dependencies:
    - base >= 4.7 && < 5
    - etna-lib
    - QuickCheck
    - smallcheck
    - leancheck
    - generic-random
    - deepseq

library:
    source-dirs: src

executables:
    rbt:
        main: Main.hs
        source-dirs: app/rbt
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-rbt
    rbt-sampler:
        main: Main.hs
        source-dirs: app/rbt-sampler
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - etna-rbt

